
package:
  name: scicat_client
  #version: 0.0.1
  version: "{{ load_setup_py_data().version }}"
  
source:
  path: ../

build:
  noarch: python
  entry_points:
    - scicat-client = scicat_client.client:cli
    - scicat-check  = scicat_client.check_saved_data:cli
    - scicat-verify = scicat_client.verify_data:cli

requirements:
  build:
    - python
    - requests
  run:
    - python
    - requests
 

about:
  home: https://github.com/paulscherrerinstitute/scicat_client
  license: GPLv3
  summary: a simple Scicat python client
  description: |
    This package provides a simple python interface to SciCat (https://scicatproject.github.io/)
